using System;
using System.Collections.Generic;
using Sirenix.OdinInspector;
using UnityEngine;

[CreateAssetMenu(fileName = "SSO_Character", menuName = "Static Scriptable/Character")]
public class SSO_Character : ScriptableObject
{
    /// <summary>
	/// Unity in-built editor function called whenever the scriptable object is updated.
    /// Used to apply change to drag immediatly to rigidbody.
	/// </summary>
	public void OnValidate() => OnSSOChanged?.Invoke();
	public Action OnSSOChanged;


	#region MOVEMENT

	[FoldoutGroup("Movement")]
	[InfoBox("Magnitude of the character direction input when walking.", InfoMessageType.None)]
	public float MaxMoveForce;

	[FoldoutGroup("Movement")]
    [PropertySpace(SpaceBefore = 15, SpaceAfter = 0)]
    [InfoBox("Minimum analog input required to start moving.", InfoMessageType.None)]
	[MinValue(0)][MaxValue(1)]
    public float MoveAnalogStart;

    [FoldoutGroup("Movement")]
	[PropertySpace(SpaceBefore = 15, SpaceAfter = 0)]
	[InfoBox("Magnitude of the up vector when jumping. Note: This value is high because the friction and drag are still being applied on this frame.", InfoMessageType.None)]
    public float JumpForce;

	[FoldoutGroup("Movement")]
	[PropertySpace(SpaceBefore = 15, SpaceAfter = 0)]
	[InfoBox("Duration during which the character is still able to jumb after start falling.", InfoMessageType.None)]
	public float CoyoteTime;

	#endregion

	#region GROUND

	[FoldoutGroup("Ground")]
	[InfoBox("Drag applied to the character if grounded. Used to slow character movement acceleration. Note: Drag is set to 0 if the character is not grounded.", InfoMessageType.None)]
	public float DragGround;

	[FoldoutGroup("Ground")]
	[PropertySpace(SpaceBefore = 15, SpaceAfter = 0)]
	[InfoBox("Friction applied to the character if grounded and not receiving movement inputs. Used to stop the character. Note: Friction is set to 0 if the character is not grounded.", InfoMessageType.None)]
	public float FrictionDeceleration;

	[FoldoutGroup("Ground")]
	[PropertySpace(SpaceBefore = 15, SpaceAfter = 0)]
	[InfoBox("Check ground & handle step on systems raycasts will only include the following layer masks.", InfoMessageType.None)]
	public LayerMask GroundLayerToInclude;

	[FoldoutGroup("Ground")]
	[PropertySpace(SpaceBefore = 15, SpaceAfter = 0)]
	[InfoBox("Width added to cast used to determine if it is triggering things.", InfoMessageType.None)]
	public float SkinWidth;

	[FoldoutGroup("Ground")]
	[PropertySpace(SpaceBefore = 15, SpaceAfter = 0)]
	[InfoBox("Maximum height of a step the character will automatically step on.", InfoMessageType.None)]
	public float StepOnHeight;

	#endregion

	#region FALL

	[FoldoutGroup("Fall")]
	[InfoBox("Duration after what the character will be destroyed.", InfoMessageType.None)]
	public float FallDeathDurationBeforeRespawn;


	[Title("Air control")]
	[FoldoutGroup("Fall")]
	[PropertyRange(0f, 10f)]
	[InfoBox("Scalar applied to the max speed while falling.", InfoMessageType.None)]
	public float AirControlScalar;

	[FoldoutGroup("Fall")]
	[PropertySpace(SpaceBefore = 15, SpaceAfter = 0)]
	[InfoBox("Duration during witch air control movement can be applied.", InfoMessageType.None)]
	public float AirControlDuration;

	[FoldoutGroup("Fall")]
	[PropertyRange(0f, 2f)]
	[PropertySpace(SpaceBefore = 15, SpaceAfter = 0)]
	[InfoBox("Percentage of the current velocity magnitude the character is allowed to preform before exiting the air control.", InfoMessageType.None)]
	public float AirControlThreshold;

	[FoldoutGroup("Fall")]
	[PropertyRange(1f, 2f)]
	[PropertySpace(SpaceBefore = 15, SpaceAfter = 0)]
	[InfoBox("Scalar used to apply drag while falling of X and Z axis.", InfoMessageType.None)]
	public float ZeroDragScalar;

	[FoldoutGroup("Fall")]
	[PropertySpace(SpaceBefore = 15, SpaceAfter = 0)]
	[InfoBox("Duration while in fall state and character stuck on the  y-axis before respawning character.", InfoMessageType.None)]
	public float StuckYDuration;

	#endregion

	#region ROPE

	[FoldoutGroup("Rope")]
	[PropertySpace(SpaceBefore = 15, SpaceAfter = 0)]
	[InfoBox("Distance the rope constraint length increases when the character enters the rope state.", InfoMessageType.None)]
	public float EntranceOffset;


	[Title("Suspension")]
	[FoldoutGroup("Rope")]
	[InfoBox("Maximum angle tolerated the character can swing with the rope (upper values are clamped onto this one).", InfoMessageType.None)]
	public float MaxPendulumAngle;

	[FoldoutGroup("Rope")]
	[PropertySpace(SpaceBefore = 15, SpaceAfter = 0)]
	[InfoBox("Angle used to determine a direction within the cercle generated by the rope condition.", InfoMessageType.None)]
	public float RopeOffsetAngle;

	[FoldoutGroup("Rope")]
	[PropertySpace(SpaceBefore = 15, SpaceAfter = 0)]
	[InfoBox("Force applied to the character direction while roped.", InfoMessageType.None)]
	public float ropeMovementForce;


	[Title("Partial")]
	[FoldoutGroup("Rope")]
	[InfoBox("Length of raycasts used to check if the character stands against a wall.", InfoMessageType.None)]
	public float AgainstWallRaycastLength;

	[FoldoutGroup("Rope")]
	[PropertySpace(SpaceBefore = 15, SpaceAfter = 0)]
	[InfoBox("Layers included in raycasts used to check if the character stands against a wall.", InfoMessageType.None)]
	public LayerMask AgainstWallLayerToInclude;

	[FoldoutGroup("Rope")]
	[PropertySpace(SpaceBefore = 15, SpaceAfter = 0)]
	[InfoBox("Force of the vector normal to the wall when jumping while suspended with a rope.", InfoMessageType.None)]
	public float JumpOffWallForce;


	[Title("Climbing")]
	[FoldoutGroup("Rope")]
	[InfoBox("Acceleration value used to determine the force to pull the character up the rope.", InfoMessageType.None)]
	public float ClimbAcceleration;

	[FoldoutGroup("Rope")]
	[PropertySpace(SpaceBefore = 15, SpaceAfter = 0)]
	[InfoBox("Maximum force the character can use to pull itself up the rope.", InfoMessageType.None)]
	public float MaxClimbSpeed;

	[FoldoutGroup("Rope")]
	[PropertySpace(SpaceBefore = 15, SpaceAfter = 0)]
	[InfoBox("Minimum legal distance between the character's position and the candidate position to enable the DOTween animation.", InfoMessageType.None)]
	public float EdgeCatchingThreshold;

	[FoldoutGroup("Rope")]
	[PropertySpace(SpaceBefore = 15, SpaceAfter = 0)]
	[InfoBox("Duration of the movement translation.", InfoMessageType.None)]
	public float EdgeCatchingDuration;

	[FoldoutGroup("Rope")]
	[PropertySpace(SpaceBefore = 15, SpaceAfter = 0)]
	[InfoBox("Distance added towards the landing point.", InfoMessageType.None)]
	public float EdgeCatchingOffset;


	[Title("Jumping")]
	[FoldoutGroup("Rope")]
	[PropertySpace(SpaceBefore = 15, SpaceAfter = 0)]
	[InfoBox("Modifier applied to the last direction on the rope when the character switches from the rope to free fall.", InfoMessageType.None)]
	public float FreeFallFromRopeModifier;

	[FoldoutGroup("Rope")]
	[PropertySpace(SpaceBefore = 15, SpaceAfter = 0)]
	[InfoBox("Modifier applied to the last direction on the rope when the character switches from the rope to jump of the rope.", InfoMessageType.None)]
	public float JumpOffRopeModifier;

	[FoldoutGroup("Rope")]
	[PropertySpace(SpaceBefore = 15, SpaceAfter = 0)]
	[InfoBox("Duration during which the character isn't able to jump again.", InfoMessageType.None)]
	public float JumpRopeDelay;


	[Title("Drag")]
	[FoldoutGroup("Rope")]
	[PropertySpace(SpaceBefore = 15, SpaceAfter = 0)]
	[InfoBox("Duration to reach the rope drag value.", InfoMessageType.None)]
	public float RopeDragDuration;

	[FoldoutGroup("Rope")]
	[PropertySpace(SpaceBefore = 15, SpaceAfter = 0)]
	[InfoBox("Maximum rope drag applied to the character.", InfoMessageType.None)]
	public float RopeDrag;

	[FoldoutGroup("Rope")]
	[PropertySpace(SpaceBefore = 15, SpaceAfter = 0)]
	[InfoBox("Apply the rope drag if the character inputs magnitude is below.", InfoMessageType.None)]
	public float MoveMagnitudeApplyDragThreshold;

	#endregion

	#region DEATH

	[FoldoutGroup("Death")]
	[InfoBox("", InfoMessageType.None)]
	public CharacterRagdoll PfCharacterRagdoll;

	#endregion

	#region GLOW

	[FoldoutGroup("Glow")]
	[InfoBox("Up offset from the character position where the glow starts to be emitted.", InfoMessageType.None)]
	public float GlowHeight;

	[FoldoutGroup("Glow")]
	[PropertySpace(SpaceBefore = 15, SpaceAfter = 0)]
	[InfoBox("Radius of the shader glow effect.", InfoMessageType.None)]
	public float GlowRadius;

	[FoldoutGroup("Glow")]
	[PropertySpace(SpaceBefore = 15, SpaceAfter = 0)]
	[InfoBox("Intensity of the shader glow effect.", InfoMessageType.None)]
	public float GlowStrength;

	[FoldoutGroup("Glow")]
	[PropertySpace(SpaceBefore = 15, SpaceAfter = 0)]
	[InfoBox("Color of the shader glow effect.", InfoMessageType.None)]
	public Color GlowColor;

	#endregion

	#region STATUS

	[FoldoutGroup("Status")]
	[InfoBox("Maximum distance the character can travel on the y-axis between two grounded position without dying.", InfoMessageType.None)]
	public float LethalHeight;


	[Title("Stun")]
	[FoldoutGroup("Status")]
	[InfoBox("Maximum distance the character can travel on the y-axis between two grounded position without being stunned.", InfoMessageType.None)]
	public float StunHeight;

	[FoldoutGroup("Status")]
	[PropertySpace(SpaceBefore = 15, SpaceAfter = 0)]
	[InfoBox("Duration of the stun status based on the distance travelled on the y-axis.", InfoMessageType.None)]
	public AnimationCurve StunDuration;

	[FoldoutGroup("Status")]
	[PropertySpace(SpaceBefore = 15, SpaceAfter = 0)]
	[InfoBox("Duration of the slow status applied after the stun status vanquishes.", InfoMessageType.None)]
	public float PostStunSlowDuration;


	[Title("Slow")]
	[FoldoutGroup("Status")]
	[InfoBox("Maximum distance the character can travel on the y-axis between two grounded position without being slowed.", InfoMessageType.None)]
	public float SlowHeight;

	[FoldoutGroup("Status")]
	[PropertySpace(SpaceBefore = 15, SpaceAfter = 0)]
	[InfoBox("Duration of the slow status based on the distance travelled on the y-axis.", InfoMessageType.None)]
	public AnimationCurve SlowDuration;

	[FoldoutGroup("Status")]
	[PropertySpace(SpaceBefore = 15, SpaceAfter = 0)]
	[InfoBox("Percentage of the character speed reduction while under the slow status based on the distance travelled on the y-axis.", InfoMessageType.None)]
	public AnimationCurve SlowPercentage;

	[FoldoutGroup("Status")]
	[PropertySpace(SpaceBefore = 15, SpaceAfter = 0)]
	[InfoBox("Maximum duration of the slow status.", InfoMessageType.None)]
	public float MaxSlowDuration;

	#endregion

	#region INTERACT

	[FoldoutGroup("Interact")]
	[InfoBox("If true, the character starts the play mode with a backpack.", InfoMessageType.None)]
	public bool StartWithBag;

	[FoldoutGroup("Interact")]
	[ShowIf("StartWithBag")]
	[PropertySpace(SpaceBefore = 15, SpaceAfter = 0)]
	[InfoBox("Prefab of the backpack. Spawned only if the `StartWithBag` debug is true.", InfoMessageType.None)]
	public Backpack PfBackpack;

	[FoldoutGroup("Interact")]
	[PropertySpace(SpaceBefore = 15, SpaceAfter = 0)]
	[InfoBox("List of string used to customize the contextual display while interacting.", InfoMessageType.None)]
	public List<InteractableFlavors> InteractableFlavors = new List<InteractableFlavors>();

	#endregion
}